import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { GithubLoginButton } from 'react-social-login-buttons';
import CornerTriangle from '../components/UI/CornerTriangle';
import AccountBanner from '../components/UI/AccountBanner';
import { useSession, signOut } from 'next-auth/react';
import useAddressbook from '../hooks/useAddressbook';
import { useEffect, useState } from 'react';
import useWeb3Modal from '/hooks/useWeb3Modal';
export default function Home() {
  const [user, setUser] = useState({});

  const { connect, address } = useWeb3Modal();
  const { data: session, status } = useSession({ required: true });
  const { addressbook } = useAddressbook(session.user.id);

  useEffect(() => {
    addressbook.find((user) => {
      session.user.id === user.discordId ? setUser(user) : null;
    });
  }, [session, addressbook]);
  return (
    <div className={styles.container}>
      <CornerTriangle origin="origin-top-right" corner={'top-0 left-0'} />
      <CornerTriangle origin="origin-bottom-left" corner={'bottom-0 right-0'} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} bg-white`}>
        <div className="flex row justify-around items-center w-60	">
          <Image
            className=" rounded-full"
            src={session.user.image}
            width={100}
            height={100}
          />
          <h1 className="text-3xl">{session.user.name}</h1>
        </div>

        <div className="w-full flex flex-row justify-center">
          <AccountBanner src={'/assets/ethereum.png'}>
            {user.address
              ? `${user.address.slice(0, 5)}...${user.address.slice(-4)}`
              : 'No Ethereum Address'}
          </AccountBanner>
          <div>
            <AccountBanner src={'/assets/github.png'}>
              {user.github ? user.github : 'No Github Username'}
            </AccountBanner>

            <GithubLoginButton />
          </div>
        </div>

        <button>{!!user ? 'Update Account' : 'Sign Up'}</button>
        <a href="https://she.energy" target="_blank" rel="noopener noreferrer">
          Powered by SHE
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </main>
    </div>
  );
}

Home.auth = true;
